### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by tannerghosen** [tannerghosen/Website#1]
- [ ] Fix how the p HTML element on index with the tag of "time" appears to shift when using custom fonts, temporary work around put in with the time being in the font-family Arial. - Mid Priority
- [ ] Put more interest into how scalability works, should look fine on mobile devices, need to see about images. - Low-Mid Priority
- [ ] Make site look more cool. Maybe bone background for some elements on a webpage? - Mid-High Priority

**Comment by tannerghosen** [comment]
Issue 1 might not be fixed without looking for someone to see the font and see if they can improve it. Changed from mid to low on that basis.

**Comment by tannerghosen** [comment]
Somehow fixing the font to be 100% fixed the problem. Looks fine on mobile now.
